apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    helm:
      parameters:
        - name: replicaCount
          value: "4"
        - name: image.tag
          value: "1.24.0-debian-12-r25"