apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    targetRevision: 19.0.3
    helm:
      parameters:
        - name: service.type
          value: "ClusterIP"