apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    helm:
      parameters:
#        - name: "image.tag"
#          value: "1.24.0-debian-12-r25"