---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  source:
    targetRevision: 13.2.0  # The Helm chart version to use
    helm:
      parameters:
        - name: replicaCount
          value: "1"
