apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  source:
    helm:
      parameters:
        - name: image.tag
          value: "1.27.4-debian-12-r7"