apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    helm:
      valueFiles:
#        - ../../releases/base/nginx-values.yaml
#        - ../../releases/v1.0.0/nginx-values.yaml
        - nginx-values.yaml