apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: app-
resources:
  - ../base

#patches:
#  - path: ./overrides/nginx-app.yaml

patchesStrategicMerge:
  - overrides/nginx-app.yaml