apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: release-v1.0.0-
resources:
  - ../base

#patches:
#  - path: ./overrides/nginx.yaml

patchesStrategicMerge:
  - ./overrides/nginx.yaml